### ISSUE TITLE
Add configuration file for mpc

### ISSUE THREAD

**Issue by ispmarin** [MusicPlayerDaemon/mpc#102]
Hi, 

I would like to have a mpc configuration file, maybe in $XDG_CONFIG_HOME/.mpc/config, so I can keep the host configuration set. I do not want to pass --host every time. Thanks

**Comment by MaxKellermann** [comment]
I think that would be overengineered when you can just set libmpdclient's environment variables, which work with every MPD client, not just mpc.

**Comment by paboum** [comment]
Wow! ncmpcpp/ncmpcpp doesn't even respect that variable ( https://github.com/ncmpcpp/ncmpcpp/issues/76 ), while MusicPlayerDaemon/ncmpc correctly utilizes config file setting for MPD host and allows overriding with env var.

**Comment by paboum** [comment]
> It's open source. If you disagree, take the source code and implement whatever you want.

Nah, I won't pollute the space with another fork of bad software just because you're incompetent and can't even politely ask for a PR. Will just use ncmpc instead or even donate there.

**Comment by sfhunter14** [comment]
Hahaha marking comments as "abuse" because an incompetent snowflake doesn't understand why config files exist. What are you, five? Now I will double my donations for all other mpd clients. I will also link this ticket to every relevant thread so that people could see what's stopping the development of this project - snowflakes.
