### ISSUE TITLE
mpc takes a long time to execute a request, even if mpd is not running

### ISSUE THREAD

**Issue by HardDie** [MusicPlayerDaemon/mpc#53]
On one of my PCs, mpc takes too long to complete the request, but ncmpcpp works as usual.
I can’t understand why this is happening.
I performed mpc with "perf record -g mpc" and got this result:
![2020-02-12-19-58-31_948x689_grim](https://user-images.githubusercontent.com/18051793/74358140-0163a580-4dd2-11ea-8a46-09aef8a9bfad.png)
And also I run mpc with time command:
╰─$ time mpc
MPD error: Connection refused
mpc  0.00s user 0.01s system 0% cpu 30.034 total
╰─$ time mpc
MPD error: Connection refused
mpc  0.00s user 0.01s system 0% cpu 30.036 total
╰─$ time mpc
MPD error: Connection refused
mpc  0.00s user 0.01s system 0% cpu 30.036 total

Do you have any suggestions?

**Comment by MaxKellermann** [comment]
What is your mpc version? What is your mpc and ncmpcpp configuration?
Your `perf report` is useless because it consumes no CPU; the process is idle. It is probably waiting for the kernel.
You can try `strace -tttT mpc` to see which system call hangs.
It has probably to do with your network, and is not a mpc bug.
A mpc bug is very unlikely, because both mpc and ncmpcpp use the same library for the network connection to MPD. So they're using different connection settings, probably because your settings are incoherent.

**Comment by HardDie** [comment]
I figured out the problem.
For some reason, mpd cannot bind to IPv4 port 6600, but binds to IPv6. I configured iptables to drop all IPv6 packets.
