### ISSUE TITLE
One-shot single mode has been added to MPD but is not available from mpc

### ISSUE THREAD

**Issue by nicoe** [MusicPlayerDaemon/mpc#71]
In this commit : https://github.com/MusicPlayerDaemon/MPD/commit/1628d801f9534ab33a711d337cdd691dca2c5710 a one shot single mode has been added to MPD. mpc does not support it.

For the toggling behaviour I guess it could work like this:
`mpc single` toggle `on`→ `off` ; `off`→ `on`; `once` → `off`

**Comment by Lovewyrm** [comment]
What does this 'one-shot' do? Is it a sort of preview? Like, maybe one can use it in the search engine window to preview a song, and after that it goes back to the playlist? or something like that? 

Because that would be really sweet. I have a lot of music in foreign languages, many I don't even speak so sometimes it would be nice to preview a song before sending it to the main playlist/queue.

**Comment by liate7** [comment]
It's a third mode for single; it acts as if single is on once, then turns off single (eg, with repeat off, it pauses at the end of the current track, then pauses; I think it repeats the current track once, then pauses with repeat on, but I'm not sure).  I mostly use it to pause at the end of a song instead of right this moment.  See the protocol document [here](https://mpd.readthedocs.io/en/latest/protocol.html?highlight=oneshot#playback-options).

**Comment by MaxKellermann** [comment]
36847ba427e939b4d8b28af0bacb11654112acb6
